name: tranhvo415-a11y-svr-pocketbase

# trigger:
#   branches:
#     include:
#       - main
#       - develop
# - release/*
# tags:
#   include:
#     - v*
# paths:
#   include:
#     - src/**
#     - docker-compose.yml
#   exclude:
#     - docs/**
#     - "**/*.md"

pr:
  branches:
    include:
      - main
      # - develop
  # paths:
  #   include:
  #     - src/**
  #   exclude:
  #     - docs/**
  # autoCancel: true

# schedules:
#   - cron: "0 2 * * *"
#     displayName: Daily 02:00 UTC
#     branches:
#       include:
#         - main
#     always: true

stages:
  - stage: deploy
    displayName: Deploy template
    jobs:
      - job: deploy_template
        displayName: tranhvo415-a11y-svr-pocketbase
        timeoutInMinutes: 60
        pool:
          vmImage: ubuntu-latest #windows-latest,macos-latest
        steps:
          - checkout: self
            fetchDepth: 1
            # submodules: recursive
            # path: s/app
          - task: NodeTool@0
            displayName: setup-nodejs
            inputs:
              versionSpec: "20.x" #"18.x","22.x"
          - script: |
              if [ -f package.json ]; then
                npm install
              else
                echo "No package.json found, skipping npm install"
              fi
              npm i -g @tltdh61/dotenvrtdb
              npm i -g @hugginroonin/runner-add-ssh
            displayName: npm-installed

          - script: |
              if [ -z "$DOTENVRTDB_URL" ]; then
                echo "DOTENVRTDB_URL is empty. Set it in Pipeline Variables or Variable Group."
                exit 1
              fi

              : > .env
              dotenvrtdb -e .env --eUrl="$DOTENVRTDB_URL" --pull
              dotenvrtdb -e .env --writefilebase64=./cloudflared-credentials.json --var=CLOUDFLARED_CREDENTIALS_JSON_BASE64
              dotenvrtdb -e .env --writefilebase64=./cloudflared-config.yml --var=CLOUDFLARED_CONFIG_YML_BASE64
              dotenvrtdb -e .env --writefilebase64=./docker-compose.yml --var=DOCKER_COMPOSE_YML_BASE64
              # dotenvrtdb -e .env --writefileraw=./custom.json --var=CUSTOM_JSON
            displayName: create-env-file
            env:
              DOTENVRTDB_URL: $(DOTENVRTDB_URL)

          - script: |
              chmod +x ./.bash/setup-bash-aliase.sh
              ./.bash/setup-bash-aliase.sh ./.env
              source "$HOME/.bash/runner-alias.env"
              source "$HOME/.bash/.bash_aliase"
              r_help
            displayName: setup-bash-aliase
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

          - script: |
              dotenvrtdb -e .env -- runner-add-ssh
            displayName: runner-add-ssh

          - script: |
              dotenvrtdb -e .env -- node ./scripts/setup-runner-prev.js
            displayName: setup-runner-prev

          - script: |
              docker compose --env-file .env up -d
              # docker compose --env-file .env -f docker-compose.prod.yml up -d
            displayName: docker-started

          - script: |
              dotenvrtdb -e .env -- node ./scripts/setup-runner-after.js
            displayName: setup-runner-after

          - script: |
              npx --yes @ongtrieuhau861457/runner-keep-alive --interval 60 --services docker
            displayName: runner-keep-alive

          - script: |
              docker compose --env-file .env down -v
              # docker compose --env-file .env down
            displayName: docker-cleanup
            condition: always()
